VPN to United States and reopen this, you will have something special 😆

# Python Programming 101

### Constants

In [ ]:
import numpy as np

print(np.array([True, 1, 2]) + np.array([3, 4, False]))

print(np.array([True, 1, 2, 3, 4, False]))

print(np.array([4, 3, 0]) + np.array([0, 2, 2]))

print(np.array([1, 1, 2]) + np.array([3, 4, -1]))

print(np.array([0, 1, 2, 3, 4, 5]))

[4 5 2]
[1 1 2 3 4 0]
[4 5 2]
[4 5 1]
[0 1 2 3 4 5]


In [ ]:
print(123)
print(98.6)
print('Hello World')
print(True) # Boolean

123
98.6
Hello World
True


For Checking hotkey, please press Ctrl-M, then press H.

### Variables

In [ ]:
x = 12.2
y = 14

In [ ]:
# Or you can
x, y = 25.6, 36.9
print(x, y)

25.6 36.9


In [ ]:
x = 100
print(x, y)

100 14


Notes: Rules for variable names
- A variable name must start with a letter or the underscore character
- A variable name cannot start with a number
- A variable name can only contain alpha-numeric characters and underscores (A-z, 0-9, and _ )
- Variable names are case-sensitive (age, Age and AGE are three different variables)

In [ ]:
# But this one is okay
π = 3.141592654
此地無銀 = 300

print(π, 此地無銀, '😂')

3.141592654 300 😂


Reference is [here](https://medium.com/data-science/why-im-coding-with-emojis-in-jupyter-notebooks-23f08585ed3d).

### Expressions

In [ ]:
# Addition
octopus = 0.5
octopus = octopus + 100
# Or you can use octopus += 2
print(octopus)

100.5


In [ ]:
octopus += 100
print(octopus)

200.5


In [ ]:
# Multiplication
kg = 440 * 12
print(kg)

5280


In [ ]:
# Division
ton = kg / 1000
print(ton)

5.28


In [ ]:
# Remainder
num = 23
quo, rem = num // 5, num % 5
print(f'{num} divided by 5 equals {quo} with remainder {rem}')

23 divided by 5 equals 4 with remainder 3


In [ ]:
# Power
print(4 ** 3)

64


In [ ]:
# Operation Order
x = 1 + 2 * 3 - 4 / 5 ** 6
print(x)
x = 1 + 2 ** 3 / 4 * 5
print(x)

6.999744
11.0


Reference is [here](https://cheatography.com/nouha-thabet/cheat-sheets/python-operators-and-booleans/).
![Week 1 colab 001.png](https://drive.google.com/uc?export=view&id=13m_geSQwMSNe43qn1AqDN66CqX3hNOfj)

### Variable Types

In [ ]:
# numeric "+"
num_add = 1 + 4
print(num_add)

5


In [ ]:
# string "+"
str_add = 'hello ' + 'there'
print(str_add)

hello there


In [ ]:
# Error
str_add = str_add + 1

NameError: name 'str_add' is not defined

In [ ]:
# Check the type
print(type(str_add))

NameError: name 'str_add' is not defined

In [ ]:
print(type('hello'))
print(type(1))

<class 'str'>
<class 'int'>


### Type Conversions

In [ ]:
print(float(99) + 100)

199.0


In [ ]:
i = 42
print(f'Type of i = {type(i)}')

f = float(i)
print(f)
print(f'Type of f = {type(f)}')

Type of i = <class 'int'>
42.0
Type of f = <class 'float'>


In [ ]:
# Error for this case
str_num_eg = '123'
print(f'Type of str_num_eg = {type(str_num_eg)}')
print(str_num_eg + 1)

Type of str_num_eg = <class 'str'>


TypeError: can only concatenate str (not "int") to str

In [ ]:
# This is okay
int_num_eg = int(str_num_eg)
print(type(int_num_eg))
print(int_num_eg + 1)

<class 'int'>
124


In [ ]:
# convert to string
print(str(int_num_eg))

123


In [ ]:
# Error
err_str2int = 'I go to make error'
err_int = int(err_str2int)

ValueError: invalid literal for int() with base 10: 'I go to make error'

### Integer Division

In [ ]:
# Outcome of integer division gives integers
print(10 // 2)

5


In [ ]:
# Outcome a float whatever they are integers or floats
print(10 / 2)
print(9 / 2)
print(99 / 100)
print(10.0 / 2.0)
print(99.0 / 100.0)

5.0
4.5
0.99
5.0
0.99


User Input

In [ ]:
name = input('Who are you? ')
print(f'Hi {name} your salary is being transferred to your wife automatically...')

KeyboardInterrupt: Interrupted by user

### Conditional Statement

In [ ]:
x = 5
print('Before 5')
if  x == 5 :
    print('Is 5')
    print('Is Still 5')
    print('Third 5')
print('Afterwards 5')
print('Before 6')
if x == 6 :
    print('Is 6')
    print('Is Still 6')
    print('Third 6')
print('Afterwards 6')
print(x)

Before 5
Is 5
Is Still 5
Third 5
Afterwards 5
Before 6
Afterwards 6
5


In [ ]:
print(x)

5


In [ ]:
if x < 2 :
    print('small')
elif x < 10 :
    print('Medium')
else :
    print('LARGE')
print('All done')
print(x)

Medium
All done
5


In [ ]:
# One line for a condition
print('small' if x < 2 else 'Medium' if x < 10 else 'LARGE')
print(x)

Medium
5


### While Loop

In [ ]:
# Countdown Player
import time
sec = 5

print('Start Count Down !')
while sec >= 0:
    print(sec)
    if sec == 0:
        break
    sec -= 0.5

print('Boom !!!')

Start Count Down !
5
4.5
4.0
3.5
3.0
2.5
2.0
1.5
1.0
0.5
0.0
Boom !!!


In [ ]:
1# Temperory Editor
lines_saved = [] # List, will be taught in Week 3

while True:
    line = input('> ')
    if line[0] == '#' :
        continue
    if line == 'done' :
        break
    lines_saved.append(line) # List, will be taught in Week 3
    print(f'appended {line}')

print('Done!')
print(lines_saved)

> 1
appended 1
> 2
appended 2
> 3
appended 3
> done
Done!
['1', '2', '3']



### For Loop

In [ ]:
# Dynamic EMail Sender
professors = ['Yuanyuan', 'Ben', 'Michael', 'Tony', 'Keith', 'Yau']

# import win32com.client as win32
# outlook = win32.Dispatch('outlook.application')
for professor in professors :
    # mail = outlook.CreateItem(0)
    # mail.To = f'{professor}@sta.cuhk.edu.hk'
    # mail.Subject = f'Happy Ghost festival !!!'
    body = f'Happy Ghost festival, {professor} !!!'
    print(body)
    # mail.Body = body
    # mail.Send()
print('Done!')

Happy Ghost festival, Yuanyuan !!!
Happy Ghost festival, Ben !!!
Happy Ghost festival, Michael !!!
Happy Ghost festival, Tony !!!
Happy Ghost festival, Keith !!!
Happy Ghost festival, Yau !!!
Done!


In [ ]:
# Find the largest value by for loop
largest_so_far = -1
print('Before', largest_so_far)
for the_num in [9, 41, 12, 3, 74, 15] :
    if the_num > largest_so_far :
        largest_so_far = the_num
    print(largest_so_far, the_num)
print('After', largest_so_far)

Before -1
9 9
41 41
41 12
41 3
74 74
74 15
After 74


### Simple Files IO

In [ ]:
# Write a file
file = open("testing.txt","w")
file.write("Hello World\n")
file.write("This is a Python Programming class\n")
file.write("Happy coding.\n")
file.write("Cheers, Alan.\n")
file.close()

In [ ]:
# please place welcome.txt before running this code
handle = open('welcome.txt')
print(handle)

FileNotFoundError: [Errno 2] No such file or directory: 'welcome.txt'

In [ ]:
# Otherwise you will get error
handle2 = open('goodbye.txt')

FileNotFoundError: [Errno 2] No such file or directory: 'goodbye.txt'

In [ ]:
# length of string includes \n and !
stuff = 'Hello\nWorld!'
print(stuff)
print(len(stuff))

Hello
World!
12


In [ ]:
# print for each line
for line in handle:
    print(line)

NameError: name 'handle' is not defined

In [ ]:
# or read all the lines
handle = open('welcome.txt')
lines = handle.read()
print(len(lines))
handle.close()

FileNotFoundError: [Errno 2] No such file or directory: 'welcome.txt'

In [ ]:
# remember to close the file after using this
handle.close()

In [ ]:
# string "+"
str_add = 'hello ' + 'there'
print(str_add)

hello there


In [ ]:
# Error - you cannot add an integer to a string directly
str_add = str_add + 1

TypeError: can only concatenate str (not "int") to str